baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
title: Alex Coelho [Blog]
author: "Alex Coelho"
email: alexcvcoelho@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Este é um blog pessoal, aqui compartilho um pouco do que eu sei com as pessoas,
  sempre com a intenção de ajudar ao próximo. Em geral gosto de postar coisas que tento fazer mas não encontro
  bons tutoriais que ensinem, então tento ajudar desta forma.
permalink: /:title/
lang: "pt-BR"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

sidebar: true                # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: false       # show the site description in the sidebar
show_title: true            # always keep the site title visible

# Styling

dark_header: false           # always keep the header dark
minimal: false               # use simpler style

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "README.md", icon: address-card}

external:                    # see http://fontawesome.com/icons
  - {title: Contato, icon: envelope, url: "mailto:alexcvcoelho@gmail.com"}
  - {title: Sobre mim, icon: github, url: "https://alexcvcoelho.github.io/cv"}
  - {title: RSS, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""      # see https://disqus.com/
#  isso_domain: ""           # see https://posativ.org/isso/

twitter_username: alexcvcoelho
github_username:  alexcvcoelho


# Build settings
remote_theme: niklasbuschmann/contrast@v2.6
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-gist

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
